version: '2'

services:

  beeprotest-db:
    restart: always
    image: percona/percona-server:5.7
    container_name: beeprotest-db
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password111
      - MYSQL_DATABASE=mautic3
      - MYSQL_USER=mautic
      - MYSQL_PASSWORD=password123
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    networks:
      - mautic-net
    ports:
      - "3308:3306"

  automationmonkey_latest:
    restart: always
    image: alainmm89/automationmonkey:latest
    container_name: automationmonkey_latest
    external_links:
      - beeprotest-db:mysql
    depends_on:
      - beeprotest-db
    ports:
      - 8080:80
    volumes:
      - mautic_data:/var/www/html
    environment:
      - MAUTIC_DB_HOST=beeprotest-db
      - MYSQL_PORT_3306_TCP=3306
      - MAUTIC_DB_USER=mautic
      - MAUTIC_DB_PASSWORD=password123
      - MAUTIC_DB_NAME=mautic3
      - MAUTIC_RUN_CRON_JOBS=true
      - MAUTIC_ADMIN_EMAIL=test@test.ch
      - MAUTIC_ADMIN_PASSWORD=madmin
    networks:
      - mautic-net

volumes:
  mysql_data:
    driver: local
  mautic_data:
    driver: local
networks:
  mautic-net:
    driver: bridge
